/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cv.and.pdf.generator;


import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.html.simpleparser.HTMLWorker;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringReader;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author sony
 */
public class Gencv extends javax.swing.JFrame {
String username,name;
boolean pers,grad,twelve,ten,tech,nontech,project,workshop,intern,acheivement,image;
String n1,a,c,e,f,m,d,g,n,h;
String b,u,y,cg;
String s,b1,y1,p;
String s1,b2,y2,p1;
String l,w,o,t;
String nt;
String p2;
String w1;
String i;
String a1;
String img;
String name1,path,zipfile;
/**
     * Creates new form Gencv
     */
    public Gencv() {
        initComponents();
    }
 public Gencv(String u,String n) {
        initComponents();
        username=u;
        name=n;
        System.out.println(name);
        System.out.println(username);
     selection1();
    }
public void selection1()
 {
     try
     {
    myconnection obj=new myconnection();
    String q="select * from tbchoice where user=?";
     PreparedStatement pst=obj.db.prepareStatement(q);
     pst.setString(1, username);
         ResultSet rs;
         rs=pst.executeQuery();
         while(rs.next())
         {
           pers=rs.getBoolean("personaldetails");
           grad=rs.getBoolean("graduationdetails");
           twelve=rs.getBoolean("twelvthdetails");
           ten=rs.getBoolean("tenthdetails");
           tech=rs.getBoolean("technicaldetails");
           nontech=rs.getBoolean("nontechnialdetails");
           project=rs.getBoolean("projectdetails");
           workshop=rs.getBoolean("workshopdetails");
           intern=rs.getBoolean("internshipdetails");
           acheivement=rs.getBoolean("achivement");
           image=rs.getBoolean("image");
         }
         System.out.println(pers);
     System.out.println(grad);
     System.out.println(tech);
     System.out.println(nontech);
     }
     
     catch(SQLException e)
     {
         System.out.println("msg"+e.getMessage());
     }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cv/and/pdf/generator/cv1.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        button1.setLabel("GENERATE CV");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setLabel("MAIL CV");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setLabel("SKIP MAIL");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)))
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
     /*try
     {
    myconnection obj=new myconnection();
    String q="select * from tbchoice where user='"+username+"'";
     PreparedStatement pst=obj.db.prepareStatement(q);
     pst.setString(1, username);
         ResultSet rs;
         rs=pst.executeQuery();
         if(rs.next())
         {
           pers=rs.getBoolean("personaldetails");
           grad=rs.getBoolean("graduationdetails");
           twelve=rs.getBoolean("twelvthdetails");
           ten=rs.getBoolean("tenthdetails");
           tech=rs.getBoolean("technicaldetails");
           nontech=rs.getBoolean("nontechnicaldetails");
           project=rs.getBoolean("projectdetails");
           workshop=rs.getBoolean("workshopdetails");
           intern=rs.getBoolean("internshipdetails");
           acheivement=rs.getBoolean("achivement");
           image=rs.getBoolean("image");
         }
         System.out.println(pers);
     System.out.println(grad);
     System.out.println(tech);
     System.out.println(nontech);
     }
     
     catch(SQLException e)
     {
         System.out.println(e.getMessage());   
     }*/
        if(name.equals("template1"))
     {
         try
         {
BufferedReader br=new BufferedReader(new FileReader("E:\\JAVA\\cv and pdf generator\\templates\\template1.html"));
            String str="";
            StringBuilder contentBuilder =new StringBuilder();
            while((str = br.readLine())!=null)
            {
                contentBuilder.append(str);
            }
            br.close();
            String content=contentBuilder.toString();
            try
            {
             myconnection obj=new myconnection();
             String q="select * from tbdetails where user=?";
             PreparedStatement pst=obj.db.prepareStatement(q);
             pst.setString(1, username);
             ResultSet rs;
             rs=pst.executeQuery();
             while(rs.next())
             {
                 n1=rs.getString("name");
                 a=rs.getString("address");
                 c=rs.getString("contact");
                 e=rs.getString("email");
                 f=rs.getString("fathername");
                 m=rs.getString("mothername");
                 d=rs.getString("dateofbirth");
                 g=rs.getString("gender");
                 n=rs.getString("nationality");
                 h=rs.getString("hobby");
             }
            }
            catch(SQLException o)
            {
                System.out.println(o.getMessage());
            }
            content=content.replace("$name",n1);
            content=content.replace("$address",a);
            content=content.replace("$contact",c);
            content=content.replace("$email",e);
            if(grad==false)
            {
                content=content.replace("$n1","none");
            }
            else
            {
                content=content.replace("$n1","inline");
                try
                {
                myconnection obj=new myconnection();
                String q="select * from tbgraduation where user='"+username+"'";
                PreparedStatement pst=obj.db.prepareStatement(q);
               // pst.setString(1, username);
                ResultSet rs;
                rs=pst.executeQuery();
                if(rs.next())
                {
                 b=rs.getString("branch");
                 u=rs.getString("university");
                 y=rs.getString("yearofpassing");
                 cg=rs.getString("cgpa"); 
                }
                        }
                catch(SQLException r)
                {
                    System.out.println(r.getMessage());
                }
                content=content.replace("$branch",b);
                content=content.replace("$university",u);
                 content=content.replace("$cgpa",cg);
                content=content.replace("$yearofpassing",y);
               }
            if(twelve==false)
            {
                content=content.replace("$n2","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbtwelve where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                        s=rs.getString("school");
                 b1=rs.getString("board");
                 y1=rs.getString("yearofpassing");
                 p=rs.getString("percentage");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n2","inline");
                content=content.replace("$board",b1);
                content=content.replace("$school",s);
                content=content.replace("$percentage",p);
                content=content.replace("$1yearofpassing",y1);
            }
             if(ten==false)
            {
                content=content.replace("$n3","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbtenth where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                        s1=rs.getString("school");
                 b2=rs.getString("board");
                 y2=rs.getString("yearofpassing");
                 p1=rs.getString("percentage");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n3","inline");
                content=content.replace("$2board",b2);
                content=content.replace("$2school",s1);
                content=content.replace("$2percentage",p1);
                content=content.replace("$2yearofpassing",y2);
            }
             if(tech==false)
            {
                content=content.replace("$n4","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbtechnical where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 l=rs.getString("language");
                 w=rs.getString("webdevelopment");
                 o=rs.getString("os");
                 t=rs.getString("tools");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n4","inline");
                content=content.replace("$languages",l);
                content=content.replace("$web",w);
                content=content.replace("$os",o);
                content=content.replace("$tools",t);
            }
             if(nontech==false)
            {
                content=content.replace("$n5","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbnontechnical where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 nt=rs.getString("nontechnical");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n5","inline");
                content=content.replace("$nontechnical",nt);
              }
             if(project==false)
            {
                content=content.replace("$n6","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbproject where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 p2=rs.getString("project");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n6","inline");
                content=content.replace("$project",p2);
              }
             if(workshop==false)
            {
                content=content.replace("$n7","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbworkshop where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 w1=rs.getString("workshop");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n7","inline");
                content=content.replace("$workshop",w1);
              }
             if(intern==false)
            {
                content=content.replace("$n8","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbinternship where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 i=rs.getString("internship");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n8","inline");
                content=content.replace("$internship",i);
              }
             if(acheivement==false)
            {
                content=content.replace("$n9","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbachievement where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 a1=rs.getString("achievement");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n9","inline");
                content=content.replace("$achievement",a1);
              }
             if(pers==false)
            {
                content=content.replace("$1n","none");
            }
            else
            {
                content=content.replace("$1n","inline");
                content=content.replace("$father",f);
                content=content.replace("$mother",m);
                content=content.replace("$date",d);
                content=content.replace("$gender",g);
                content=content.replace("$nationality",n);
                content=content.replace("$hobby",h);
              }
             content=content.replace("$name",n1);
             
             name1="E:\\JAVA\\cv and pdf generator\\cv1.html";
            File f=new File(name1);
            BufferedWriter bw =new BufferedWriter(new FileWriter(f));
            bw.write(content);
            bw.close();
            JOptionPane.showMessageDialog(this,"YOUR CV IN HTML FORMAT IS GENERATED");
         }
        catch(Exception e)
        {
            System.out.println(e.getMessage());    
        }
         path = "E:\\JAVA\\cv and pdf generator\\cv1.pdf";
            PdfWriter pdfWriter = null;
         Document document = new Document();
            try {
                pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(
                        path));
            } catch (DocumentException ex) {
              System.out.print("HTML file close problem:" + ex.getMessage());
            } catch (FileNotFoundException ex) {
                System.out.print("HTML file close problem:" + ex.getMessage());
            }
            document.open();
            HTMLWorker htmlWorker = new HTMLWorker(document);
            String str1 = "";
            StringBuilder contentBuilder1 = new StringBuilder();
            BufferedReader in = null;
            try {
                in = new BufferedReader(new FileReader(name1));
                
                while ((str1 = in.readLine()) != null) {
                    
                    contentBuilder1.append(str1);
                    
                }
            } catch (IOException e) {
                System.out.print("HTML file close problem:" + e.getMessage());
            } 
                try {
                    in.close();
                } catch (IOException ex) {
                    System.out.println(ex.getMessage());
                }
                String content1 = contentBuilder1.toString();
            try {
            htmlWorker.parse(new StringReader(content1));
        } catch (IOException ex) {
           System.out.print("HTML file close problem:" + ex.getMessage());
        }
             document.close();
            JOptionPane.showMessageDialog(this,"YOUR CV IN PDF FORMAT IS GENERATED");

            zipfile = "E:\\JAVA\\cv and pdf generator\\cv1.zip"; 
         String[] srcFiles = {name1,path}; 
   try { 
             // create byte buffer 
             byte[] buffer = new byte[1024]; 
             FileOutputStream fos = new FileOutputStream(zipfile); 
            ZipOutputStream zos = new ZipOutputStream(fos); 
             for (int i=0; i < srcFiles.length; i++) { 
                 File srcFile = new File(srcFiles[i]); 
                 FileInputStream fis = new FileInputStream(srcFile); 
                 // begin writing a new ZIP entry, positions the stream to the start of the entry data 
                 zos.putNextEntry(new ZipEntry(srcFile.getName())); 
                 int length; 
                 while ((length = fis.read(buffer)) > 0) { 
                     zos.write(buffer, 0, length); 
                 } 
                 zos.closeEntry(); 
                 // close the InputStream 
                 fis.close(); 
             } 
             // close the ZipOutputStream 
    zos.close();          } 
         catch (IOException ioe) { 
             System.out.println("Error creating zip file: " + ioe); 
         }
    JOptionPane.showMessageDialog(this,"YOUR CV IN ZIP FORMAT IS GENERATED");
}
     else if(name.equals("template2"))
     {
         try
         {
BufferedReader br=new BufferedReader(new FileReader("E:\\JAVA\\cv and pdf generator\\templates\\template2.html"));
            String str="";
            StringBuilder contentBuilder =new StringBuilder();
            while((str = br.readLine())!=null)
            {
                contentBuilder.append(str);
            }
            br.close();
            String content=contentBuilder.toString();
            try
            {
             myconnection obj=new myconnection();
             String q="select * from tbdetails where user='"+username+"'";
             PreparedStatement pst=obj.db.prepareStatement(q);
             //pst.setString(1, username);
             ResultSet rs;
             rs=pst.executeQuery();
             if(rs.next())
             {
                 n1=rs.getString("name");
                 a=rs.getString("address");
                 c=rs.getString("contact");
                 e=rs.getString("email");
                 f=rs.getString("fathername");
                 m=rs.getString("mothername");
                 d=rs.getString("dateofbirth");
                 g=rs.getString("gender");
                 n=rs.getString("nationality");
                 h=rs.getString("hobby");
             }
            }
            catch(SQLException o)
            {
                System.out.println(o.getMessage());
            }
            content=content.replace("$name",n1);
            content=content.replace("$address",a);
            content=content.replace("$contact",c);
            content=content.replace("$email",e);
            if(image==false)
            {
                content=content.replace("$2n","none");
            }
            else
            {
                 try
                {
                myconnection obj=new myconnection();
                String q="select * from tbimage where user='"+username+"'";
                PreparedStatement pst=obj.db.prepareStatement(q);
               // pst.setString(1, username);
                ResultSet rs;
                rs=pst.executeQuery();
                if(rs.next())
                {
                img=rs.getString("imgname"); 
                }
                        }
                catch(SQLException r)
                {
                    System.out.println(r.getMessage());
                }
                content=content.replace("$2n","inline");
                 content=content.replace("$img",img);
            }
            if(grad==false)
            {
                content=content.replace("$n1","none");
            }
            else
            {
                content=content.replace("$n1","inline");
                try
                {
                myconnection obj=new myconnection();
                String q="select * from tbgraduation where user='"+username+"'";
                PreparedStatement pst=obj.db.prepareStatement(q);
                //pst.setString(1, username);
                ResultSet rs;
                rs=pst.executeQuery();
                if(rs.next())
                {
                 b=rs.getString("branch");
                 u=rs.getString("university");
                 y=rs.getString("yearofpassing");
                 cg=rs.getString("cgpa"); 
                }
                        }
                catch(SQLException r)
                {
                    System.out.println(r.getMessage());
                }
                content=content.replace("$branch",b);
                content=content.replace("$university",u);
                 content=content.replace("$cgpa",cg);
                content=content.replace("$yearofpassing",y);
               }
            if(twelve==false)
            {
                content=content.replace("$n2","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbtwelve where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                        s=rs.getString("school");
                 b1=rs.getString("board");
                 y1=rs.getString("yearofpassing");
                 p=rs.getString("percentage");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n2","inline");
                content=content.replace("$board",b1);
                content=content.replace("$school",s);
                content=content.replace("$percentage",p);
                content=content.replace("$1yearofpassing",y1);
            }
             if(ten==false)
            {
                content=content.replace("$n3","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbtenth where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                        s1=rs.getString("school");
                 b2=rs.getString("board");
                 y2=rs.getString("yearofpassing");
                 p1=rs.getString("percentage");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n3","inline");
                content=content.replace("$2board",b2);
                content=content.replace("$2school",s1);
                content=content.replace("$2percentage",p1);
                content=content.replace("$2yearofpassing",y2);
            }
             if(tech==false)
            {
                content=content.replace("$n4","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbtechnical where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 l=rs.getString("language");
                 w=rs.getString("webdevelopment");
                 o=rs.getString("os");
                 t=rs.getString("tools");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n4","inline");
                content=content.replace("$languages",l);
                content=content.replace("$web",w);
                content=content.replace("$os",o);
                content=content.replace("$tools",t);
            }
             if(nontech==false)
            {
                content=content.replace("$n5","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbnontechnical where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 nt=rs.getString("nontechnical");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n5","inline");
                content=content.replace("$nontechnical",nt);
              }
             if(project==false)
            {
                content=content.replace("$n6","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbproject where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 p2=rs.getString("project");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n6","inline");
                content=content.replace("$project",p2);
              }
             if(workshop==false)
            {
                content=content.replace("$n7","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbworkshop where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 w1=rs.getString("workshop");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n7","inline");
                content=content.replace("$workshop",w1);
              }
             if(intern==false)
            {
                content=content.replace("$n8","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbinternship where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 i=rs.getString("internship");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n8","inline");
                content=content.replace("$internship",i);
              }
             if(acheivement==false)
            {
                content=content.replace("$n9","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbachievement where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 a1=rs.getString("achievement");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n9","inline");
                content=content.replace("$achievement",a1);
              }
             if(pers==false)
            {
                content=content.replace("$1n","none");
            }
            else
            {
                content=content.replace("$1n","inline");
                content=content.replace("$father",f);
                content=content.replace("$mother",m);
                content=content.replace("$date",d);
                content=content.replace("$gender",g);
                content=content.replace("$nationality",n);
                content=content.replace("$hobby",h);
              }
             content=content.replace("$name",n1);
             
             name1="E:\\JAVA\\cv and pdf generator\\cv2.html";
            File f=new File(name1);
            BufferedWriter bw =new BufferedWriter(new FileWriter(f));
            bw.write(content);
            bw.close();
            JOptionPane.showMessageDialog(this,"YOUR CV IN HTML FORMAT IS GENERATED");
         }
        catch(Exception e)
        {
            System.out.println(e.getMessage());    
        }
          path = "E:\\JAVA\\cv and pdf generator\\cv2.pdf";
            PdfWriter pdfWriter = null;
         Document document = new Document();
            try {
                pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(
                        path));
            } catch (DocumentException ex) {
              System.out.print("HTML file close problem:" + ex.getMessage());
            } catch (FileNotFoundException ex) {
                System.out.print("HTML file close problem:" + ex.getMessage());
            }
            document.open();
            HTMLWorker htmlWorker = new HTMLWorker(document);
            String str1 = "";
            StringBuilder contentBuilder1 = new StringBuilder();
            BufferedReader in = null;
            try {
                in = new BufferedReader(new FileReader(name1));
                
                while ((str1 = in.readLine()) != null) {
                    
                    contentBuilder1.append(str1);
                    
                }
            } catch (IOException e) {
                System.out.print("HTML file close problem:" + e.getMessage());
            } 
                try {
                    in.close();
                } catch (IOException ex) {
                    System.out.println(ex.getMessage());
                }
                String content1 = contentBuilder1.toString();
            try {
            htmlWorker.parse(new StringReader(content1));
        } catch (IOException ex) {
           System.out.print("HTML file close problem:" + ex.getMessage());
        }
             document.close();
            JOptionPane.showMessageDialog(this,"YOUR CV IN PDF FORMAT IS GENERATED");

            zipfile = "E:\\JAVA\\cv and pdf generator\\cv2.zip"; 
         String[] srcFiles = {name1,path}; 
   try { 
             // create byte buffer 
             byte[] buffer = new byte[1024]; 
             FileOutputStream fos = new FileOutputStream(zipfile); 
            ZipOutputStream zos = new ZipOutputStream(fos); 
             for (int i=0; i < srcFiles.length; i++) { 
                 File srcFile = new File(srcFiles[i]); 
                 FileInputStream fis = new FileInputStream(srcFile); 
                 // begin writing a new ZIP entry, positions the stream to the start of the entry data 
                 zos.putNextEntry(new ZipEntry(srcFile.getName())); 
                 int length; 
                 while ((length = fis.read(buffer)) > 0) { 
                     zos.write(buffer, 0, length); 
                 } 
                 zos.closeEntry(); 
                 // close the InputStream 
                 fis.close(); 
             } 
             // close the ZipOutputStream 
    zos.close();          } 
         catch (IOException ioe) { 
             System.out.println("Error creating zip file: " + ioe); 
         }
    JOptionPane.showMessageDialog(this,"YOUR CV IN ZIP FORMAT IS GENERATED");
}
 else if(name.equals("template3"))
     {
         try
         {
BufferedReader br=new BufferedReader(new FileReader("E:\\JAVA\\cv and pdf generator\\templates\\template3.html"));
            String str="";
            StringBuilder contentBuilder =new StringBuilder();
            while((str = br.readLine())!=null)
            {
                contentBuilder.append(str);
            }
            br.close();
            String content=contentBuilder.toString();
            try
            {
             myconnection obj=new myconnection();
             String q="select * from tbdetails where user='"+username+"'";
             PreparedStatement pst=obj.db.prepareStatement(q);
            // pst.setString(1, username);
             ResultSet rs;
             rs=pst.executeQuery();
             if(rs.next())
             {
                 n1=rs.getString("name");
                 a=rs.getString("address");
                 c=rs.getString("contact");
                 e=rs.getString("email");
                 f=rs.getString("fathername");
                 m=rs.getString("mothername");
                 d=rs.getString("dateofbirth");
                 g=rs.getString("gender");
                 n=rs.getString("nationality");
                 h=rs.getString("hobby");
             }
            }
            catch(SQLException o)
            {
                System.out.println(o.getMessage());
            }
           try
                {
                myconnection obj=new myconnection();
                String q="select * from tbgraduation where user='"+username+"'";
                PreparedStatement pst=obj.db.prepareStatement(q);
                //pst.setString(1, username);
                ResultSet rs;
                rs=pst.executeQuery();
                if(rs.next())
                {
                 b=rs.getString("branch");
                 u=rs.getString("university");
                 y=rs.getString("yearofpassing");
                 cg=rs.getString("cgpa"); 
                }
                        }
                catch(SQLException r)
                {
                    System.out.println(r.getMessage());
                }
             content=content.replace("$name",n1);
            content=content.replace("$discipline",b);
            content=content.replace("$email",e);
            content=content.replace("$address",a);    
             content=content.replace("$contact",c);  
             if(ten==false)
            {
                content=content.replace("$f1","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbtenth where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                        s1=rs.getString("school");
                 b2=rs.getString("board");
                 y2=rs.getString("yearofpassing");
                 p1=rs.getString("percentage");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$f1","inline");
                content=content.replace("$2board",b2);
                content=content.replace("$2school",s1);
                content=content.replace("$2percentage",p1);
                content=content.replace("$2yearofpassing",y2);
            }
             if(twelve==false)
            {
                content=content.replace("$f2","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbtwelve where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                        s=rs.getString("school");
                 b1=rs.getString("board");
                 y1=rs.getString("yearofpassing");
                 p=rs.getString("percentage");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$f2","inline");
                content=content.replace("$board",b1);
                content=content.replace("$school",s);
                content=content.replace("$percentage",p);
                content=content.replace("$1yearofpassing",y1);
            }
             
            if(grad==false)
            {
                content=content.replace("$f3","none");
            }
            else
            {
                content=content.replace("$f3","inline");
                content=content.replace("$branch",b);
                content=content.replace("$university",u);
                 content=content.replace("$cgpa",cg);
                content=content.replace("$yearofpassing",y);
               }
             if(pers==false)
            {
                content=content.replace("$f4","none");
            }
            else
            {
                content=content.replace("$f4","inline");
                content=content.replace("$father",f);
                content=content.replace("$mother",m);
                content=content.replace("$date",d);
                content=content.replace("$gender",g);
                content=content.replace("$nationality",n);
                content=content.replace("$hobby",h);
              }
                 if(tech==false)
            {
                content=content.replace("$f5","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbtechnical where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 l=rs.getString("language");
                 w=rs.getString("webdevelopment");
                 o=rs.getString("os");
                 t=rs.getString("tools");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$f5","inline");
                content=content.replace("$languages",l);
                content=content.replace("$web",w);
                content=content.replace("$os",o);
                content=content.replace("$tools",t);
            }
                  if(project==false)
            {
                content=content.replace("$f6","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbproject where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 p2=rs.getString("project");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$f6","inline");
                content=content.replace("$project",p2);
              }
             if(workshop==false)
            {
                content=content.replace("$f7","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbworkshop where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 w1=rs.getString("workshop");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$f7","inline");
                content=content.replace("$workshop",w1);
              }
             if(acheivement==false)
            {
                content=content.replace("$f8","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbachievement where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 a1=rs.getString("achievement");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$f8","inline");
                content=content.replace("$achievement",a1);
              }
             if(intern==false)
            {
                content=content.replace("$f9","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbinternship where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 i=rs.getString("internship");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$f9","inline");
                content=content.replace("$internship",i);
              }
            content=content.replace("$email",e);
             content=content.replace("$contact",c);
             content=content.replace("$dob",d);
             content=content.replace("$batch",y);
             name1="E:\\JAVA\\cv and pdf generator\\cv3.html";
            File f=new File(name1);
            BufferedWriter bw =new BufferedWriter(new FileWriter(f));
            bw.write(content);
            bw.close();
            JOptionPane.showMessageDialog(this,"YOUR CV IN HTML FORMAT IS GENERATED");
         }
        catch(Exception e)
        {
            System.out.println(e.getMessage());    
        }
         path = "E:\\JAVA\\cv and pdf generator\\cv3.pdf";
            PdfWriter pdfWriter = null;
         Document document = new Document();
            try {
                pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(
                        path));
            } catch (DocumentException ex) {
              System.out.print("HTML file close problem:" + ex.getMessage());
            } catch (FileNotFoundException ex) {
                System.out.print("HTML file close problem:" + ex.getMessage());
            }
            document.open();
            HTMLWorker htmlWorker = new HTMLWorker(document);
            String str1 = "";
            StringBuilder contentBuilder1 = new StringBuilder();
            BufferedReader in = null;
            try {
                in = new BufferedReader(new FileReader(name1));
                
                while ((str1 = in.readLine()) != null) {
                    
                    contentBuilder1.append(str1);
                    
                }
            } catch (IOException e) {
                System.out.print("HTML file close problem:" + e.getMessage());
            } 
                try {
                    in.close();
                } catch (IOException ex) {
                    System.out.println(ex.getMessage());
                }
                String content1 = contentBuilder1.toString();
            try {
            htmlWorker.parse(new StringReader(content1));
        } catch (IOException ex) {
           System.out.print("HTML file close problem:" + ex.getMessage());
        }
             document.close();
            JOptionPane.showMessageDialog(this,"YOUR CV IN PDF FORMAT IS GENERATED");

            zipfile = "E:\\JAVA\\cv and pdf generator\\cv3.zip"; 
         String[] srcFiles = {name1,path}; 
   try { 
             // create byte buffer 
             byte[] buffer = new byte[1024]; 
             FileOutputStream fos = new FileOutputStream(zipfile); 
            ZipOutputStream zos = new ZipOutputStream(fos); 
             for (int i=0; i < srcFiles.length; i++) { 
                 File srcFile = new File(srcFiles[i]); 
                 FileInputStream fis = new FileInputStream(srcFile); 
                 // begin writing a new ZIP entry, positions the stream to the start of the entry data 
                 zos.putNextEntry(new ZipEntry(srcFile.getName())); 
                 int length; 
                 while ((length = fis.read(buffer)) > 0) { 
                     zos.write(buffer, 0, length); 
                 } 
                 zos.closeEntry(); 
                 // close the InputStream 
                 fis.close(); 
             } 
             // close the ZipOutputStream 
    zos.close();          } 
         catch (IOException ioe) { 
             System.out.println("Error creating zip file: " + ioe); 
         }
    JOptionPane.showMessageDialog(this,"YOUR CV IN ZIP FORMAT IS GENERATED");
         
}   
     else if(name.equals("template4"))
     {
         try
         {
BufferedReader br=new BufferedReader(new FileReader("E:\\JAVA\\cv and pdf generator\\templates\\template4.html"));
            String str="";
            StringBuilder contentBuilder =new StringBuilder();
            while((str = br.readLine())!=null)
            {
                contentBuilder.append(str);
            }
            br.close();
            String content=contentBuilder.toString();
            try
            {
             myconnection obj=new myconnection();
             String q="select * from tbdetails where user=?";
             PreparedStatement pst=obj.db.prepareStatement(q);
             pst.setString(1, username);
             ResultSet rs;
             rs=pst.executeQuery();
             if(rs.next())
             {
                 n1=rs.getString("name");
                 a=rs.getString("address");
                 c=rs.getString("contact");
                 e=rs.getString("email");
                 f=rs.getString("fathername");
                 m=rs.getString("mothername");
                 d=rs.getString("dateofbirth");
                 g=rs.getString("gender");
                 n=rs.getString("nationality");
                 h=rs.getString("hobby");
             }
            }
            catch(SQLException o)
            {
                System.out.println(o.getMessage());
            }
           try
                {
                myconnection obj=new myconnection();
                String q="select * from tbgraduation where user='"+username+"'";
                PreparedStatement pst=obj.db.prepareStatement(q);
                //pst.setString(1, username);
                ResultSet rs;
                rs=pst.executeQuery();
                if(rs.next())
                {
                 b=rs.getString("branch");
                 u=rs.getString("university");
                 y=rs.getString("yearofpassing");
                 cg=rs.getString("cgpa"); 
                }
                        }
                catch(SQLException r)
                {
                    System.out.println(r.getMessage());
                }
             content=content.replace("$name",n1);
            content=content.replace("$branch",b);
            content=content.replace("$email",e);
            content=content.replace("$address",a);    
             content=content.replace("$contact",c);  
              if(grad==false)
            {
                content=content.replace("$n1","none");
            }
            else
            {
                content=content.replace("$n1","inline");
                content=content.replace("$branch",b);
                content=content.replace("$university",u);
                 content=content.replace("$cgpa",cg);
                content=content.replace("$yearofpassing",y);
               }
              if(twelve==false)
            {
                content=content.replace("$n2","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbtwelve where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                        s=rs.getString("school");
                 b1=rs.getString("board");
                 y1=rs.getString("yearofpassing");
                 p=rs.getString("percentage");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n2","inline");
                content=content.replace("$board",b1);
                content=content.replace("$school",s);
                content=content.replace("$percentage",p);
                content=content.replace("$1yearofpassing",y1);
            }
             if(ten==false)
            {
                content=content.replace("$n3","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbtenth where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                        s1=rs.getString("school");
                 b2=rs.getString("board");
                 y2=rs.getString("yearofpassing");
                 p1=rs.getString("percentage");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$n3","inline");
                content=content.replace("$2board",b1);
                content=content.replace("$2school",s);
                content=content.replace("$2percentage",p);
                content=content.replace("$2yearofpassing",y1);
            }
             if(tech==false)
            {
                content=content.replace("$f2","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbtechnical where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 l=rs.getString("language");
                 w=rs.getString("webdevelopment");
                 o=rs.getString("os");
                 t=rs.getString("tools");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$f2","inline");
                content=content.replace("$languages",l);
                content=content.replace("$web",w);
                content=content.replace("$os",o);
                content=content.replace("$tools",t);
            }
             if(nontech==false)
            {
                content=content.replace("$f3","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbnontechnical where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 nt=rs.getString("nontechnical");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$f3","inline");
                content=content.replace("$nontechnical",nt);
              }
             if(pers==false)
            {
                content=content.replace("$f4","none");
            }
            else
            {
                content=content.replace("$f4","inline");
                content=content.replace("$father",f);
                content=content.replace("$mother",m);
                content=content.replace("$date",d);
                content=content.replace("$gender",g);
                content=content.replace("$nationality",n);
                content=content.replace("$hobby",h);
              }
                 
                  if(project==false)
            {
                content=content.replace("$f5","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbproject where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 p2=rs.getString("project");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$f5","inline");
                content=content.replace("$project",p2);
              }
             if(workshop==false)
            {
                content=content.replace("$f6","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbworkshop where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 w1=rs.getString("workshop");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$f6","inline");
                content=content.replace("$work",w1);
              }
             
             if(intern==false)
            {
                content=content.replace("$f8","none");
            }
            else
            {
                try
                {
                    myconnection obj=new myconnection();
                    String q="select * from tbinternship where user='"+username+"'";
                    PreparedStatement pst=obj.db.prepareStatement(q);
                    ResultSet rs;
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                 i=rs.getString("internship");
                    }
                }
                catch(SQLException t)
                {
                    System.out.println(t.getMessage());
                }
                content=content.replace("$f8","inline");
                content=content.replace("$intern",i);
              }
            content=content.replace("$email",e);
             content=content.replace("$contact",c);
             content=content.replace("$dob",d);
             content=content.replace("$batch",y);
             name1="E:\\JAVA\\cv and pdf generator\\cv4.html";
            File f=new File(name1);
            BufferedWriter bw =new BufferedWriter(new FileWriter(f));
            bw.write(content);
            bw.close();
            JOptionPane.showMessageDialog(this,"YOUR CV IN HTML FORMAT IS GENERATED");
         }
        catch(Exception e)
        {
            System.out.println(e.getMessage());    
        }
          path = "E:\\JAVA\\cv and pdf generator\\cv4.pdf";
            PdfWriter pdfWriter = null;
         Document document = new Document();
            try {
                pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(
                        path));
            } catch (DocumentException ex) {
              System.out.print("HTML file close problem:" + ex.getMessage());
            } catch (FileNotFoundException ex) {
                System.out.print("HTML file close problem:" + ex.getMessage());
            }
            document.open();
            HTMLWorker htmlWorker = new HTMLWorker(document);
            String str1 = "";
            StringBuilder contentBuilder1 = new StringBuilder();
            BufferedReader in = null;
            try {
                in = new BufferedReader(new FileReader(name1));
                
                while ((str1 = in.readLine()) != null) {
                    
                    contentBuilder1.append(str1);
                    
                }
            } catch (IOException e) {
                System.out.print("HTML file close problem:" + e.getMessage());
            } 
                try {
                    in.close();
                } catch (IOException ex) {
                    System.out.println(ex.getMessage());
                }
                String content1 = contentBuilder1.toString();
            try {
            htmlWorker.parse(new StringReader(content1));
        } catch (IOException ex) {
           System.out.print("HTML file close problem:" + ex.getMessage());
        }
             document.close();
            JOptionPane.showMessageDialog(this,"YOUR CV IN PDF FORMAT IS GENERATED");

            zipfile = "E:\\JAVA\\cv and pdf generator\\cv4.zip"; 
         String[] srcFiles = {name1,path}; 
   try { 
             // create byte buffer 
             byte[] buffer = new byte[1024]; 
             FileOutputStream fos = new FileOutputStream(zipfile); 
            ZipOutputStream zos = new ZipOutputStream(fos); 
             for (int i=0; i < srcFiles.length; i++) { 
                 File srcFile = new File(srcFiles[i]); 
                 FileInputStream fis = new FileInputStream(srcFile); 
                 // begin writing a new ZIP entry, positions the stream to the start of the entry data 
                 zos.putNextEntry(new ZipEntry(srcFile.getName())); 
                 int length; 
                 while ((length = fis.read(buffer)) > 0) { 
                     zos.write(buffer, 0, length); 
                 } 
                 zos.closeEntry(); 
                 // close the InputStream 
                 fis.close(); 
             } 
             // close the ZipOutputStream 
    zos.close();          } 
         catch (IOException ioe) { 
             System.out.println("Error creating zip file: " + ioe); 
         }
    JOptionPane.showMessageDialog(this,"YOUR CV IN ZIP FORMAT IS GENERATED");
}
     try
     {
         myconnection obj=new myconnection();
         String q="insert into tbname(user,name,pdf,zip) values(?,?,?,?)";
         PreparedStatement pst=obj.db.prepareStatement(q);
         pst.setString(1, username);
         pst.setString(2, name1);
         pst.setString(3, path);
         pst.setString(4, zipfile);
         pst.executeUpdate();
     }
     catch(SQLException e)
     {
         System.out.println(e.getMessage());
     }
     
// TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
Mailcv obj=new Mailcv(username);
obj.setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
Feedback obj=new Feedback();
obj.setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gencv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gencv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gencv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gencv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gencv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
